name: Build And Deploy WCT Stats restore
on:
  push:
    branches:
      - main
    paths:
      - 'restore/**'


jobs:
  build-restore-image:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: bump version
        run: |
          echo "Bumping version..."
          VERSION=$(cat restore/version.txt)

          IFS='.' read -r major minor  <<< "$VERSION"    
          COMMIT_MSG=$(git log -1 --pretty=%B)

          echo "Commit message: $COMMIT_MSG"

          # Determine bump type
          if echo "$COMMIT_MSG" | grep -iqE "MAJOR|BREAKING"; then
            major=$((major + 1))
            minor=0
            BUMP_TYPE="major"
          else
            minor=$((minor + 1))
            BUMP_TYPE="minor"
          fi

          NEW_VERSION="$major.$minor"
          echo "Bumped $BUMP_TYPE version: $VERSION â†’ $NEW_VERSION"      
          
          echo "$NEW_VERSION" > restore/version.txt
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV


      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build and push restore image
        uses: docker/build-push-action@v2
        with:
          progress: plain        
          platforms: linux/amd64,linux/arm64
          context: restore
          push: true
          tags: |
            ghcr.io/shayops2/wct-stats-mongo-restore:latest 
            ghcr.io/shayops2/wct-stats-mongo-restore:${{ env.VERSION }}

      - name: Commit, pull, and push version bump
        uses: mgrybyk-org/git-commit-pull-push-action@v1
        with:
          branch: main                       
          commit_message: "Bump restore version to ${{ env.VERSION }} [skip ci]"
          pull_args: --rebase -X theirs            

